name: ptra_mobile
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.6

  # Flavoriz
  flutter_flavorizr: ^2.2.1

  # Routing
  go_router: ^12.1.1

  # Generators
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  injectable: ^2.3.2
  
  retrofit_generator: ^8.0.4

  # Networking
  internet_connection_checker: ^1.0.0+1
  retrofit: ^4.0.3
  dio: ^5.4.0
  # web_socket_channel: 2.4.0
  
  # Local Storage
  flutter_secure_storage: ^9.0.0
  
  # State Management
  flutter_riverpod: ^2.4.9
  
  # Testing
  mocktail: ^1.0.1
  badges: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linter
  flutter_lints: ^3.0.1

  # Generators
  build_runner: ^2.4.7
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # fonts:
